linkchecker/linkchecker

linkcheck/configuration/__init__.py
The one test failure in Travis happens in TestConsole.test_internal_error, but only if you have the argcomplete package installed.
This was a real bug in error reporting code.
Fixes #7.
=> Fix TypeError: hasattr(): attribute name must be string

setup.py
This makes 'pip install' install everything that's needed for
LinkChecker to actually work.
Fixes #12.
=> Add install_requires for setuptools

linkcheck/plugins/httpheaderinfo.py
This is a trivial fix for the old issue 690 (https://github.com/wummel/linkchecker/issues/690) The problem is caused by a change in the behaviour of CaseInsensitiveDict from the requests library. In some versions this returns lower-cased keys, in others mixed case.
=> Force header names to lower to allow for CaseInsensitiveDict variability

.gitignore, .travis.yml, tests/checker/data/http.html.result, tests/checker/test_file.py, tests/checker/test_http.py, tests/checker/test_https.py, tox.ini
https://pypi.python.org/pypi/tox is a Python testing tool that lets you run
tests without polluting your system environment or managing virtualenvs by
hand.  It is especially invaluable if you want to support multiple Python
versions (e.g. 2.7 and 3.x).
The way tox normally works is
- it builds a source distribution with `python setup.py sdist`
- it installs the sdist with `pip instlal dist/package-version.tar.gz`
- it runs the tests
and so it also checks that your sdists are complete.
=> Add a tox.ini

linkcheck/checker/urlbase.py, linkcheck/url.py, tests/test_url.py
Allow linkchecker to process wayback style URLs, ie URLs used by web archives which contain a full scheme embedded in the query string, like:
http://web.archive.org/web/20010106023100/http://www.bbc.co.uk/
By default linkchecker url-encodes the second http[s]://, making the URL invalid. 
The use case for this feature is web archives wanting to crawl their archived sites as part of QA. This is very much a minority use, so the option has been made configurable with a default value 'off'.
=> Wayback urls

linkcheck/HtmlParser/htmllex.c, linkcheck/HtmlParser/htmllex.l, linkcheck/HtmlParser/htmlparse.c, linkcheck/HtmlParser/htmlparse.h, linkcheck/HtmlParser/htmlparse.y
Fixes a bunch of warnings like
htmlparse.y:509:25: warning: operation on ‘self->userData->buf’ may be undefined [-Wsequence-point]
htmlparse.y:518:29: warning: operation on ‘self->userData->tmp_buf’ may be undefined [-Wsequence-point]
which were a result of (macro-expanded) code like this (simplified):
if ((tmp = (tmp = PyMem_Realloc(...))) == NULL) return NULL;
The PyMem_Resize(p, ...) macro assigns the new value to p before
returning it, so there's no need to assign it again.
See http://bugs.python.org/issue1668036 for evidence (from 2007) that
this is indeed a documented side-effect of the macro API.
This fixes one half of #34.
The diff is not very pretty because we have bison-generated code in our
Git repository.
=> Fix "operation on ... may be undefined" [-Wsequence-point] warnings

linkcheck/HtmlParser/htmlparse.c, linkcheck/HtmlParser/htmlparse.y
The warnings looked like this:
htmlparse.c: In function ‘yyparse’:
htmlparse.c:1810:18: warning: passing argument 1 of ‘yyerror’ from incompatible pointer type [-Wincompatible-pointer-types]
htmlparse.y:40:13: note: expected ‘PyObject ** {aka struct _object **}’ but argument is of type ‘PyObject * {aka struct _object *}’
htmlparse.c:1927:12: warning: passing argument 1 of ‘yyerror’ from incompatible pointer type [-Wincompatible-pointer-types]
htmlparse.y:40:13: note: expected ‘PyObject ** {aka struct _object **}’ but argument is of type ‘PyObject * {aka struct _object *}’
The argument is not used, so it doesn't really matter what pointer type
it is.
Fixes #34.
=> Fix incompatible pointer type warnings

linkcheck/cache/results.py, linkcheck/cache/urlqueue.py, tests/cache/test_urlqueue.py, tests/checker/data/file.html.result, tests/checker/data/http.html.result, tests/checker/data/http_lowercase.html.result, tests/checker/data/http_slash.html.result, tests/checker/data/misc.html.result, tests/checker/test_file.py, tests/checker/test_http_redirect.py
As mentioned in #608, Linkchecker does multiple checks for one URL. It is caused by inconsistent use of cache. The URL is added to the queue when checking page, but it doesn't get to cache until the moment of checking the URL itself. In the meantime, it can be added to queue multiple times.
This PR should fix it.
=> Fix cache: Don't check one url multiple times

requirements.txt, setup.py
Linkchecker doesn't work with the latest requests
see #74
=> Temporary fix

linkchecker
Current output:
```
$ linkchecker --version
INFO linkcheck.cmdline 2017-09-11 12:46:55,167 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4 released xx.xx.xxxx
Copyright (C) 2000-2014 Bastian Kleineidam
```
Please note: I have not tested this very minor change proposal, just used github web ui for editing etc, but I mean what should go wrong ;-)
=> Avoid info log 'Checking intern URLs only…' when calling 'linkchecker --version'

linkcheck/checker/httpurl.py
newer requests do not expose the internal SSL socket object so we
cannot verify certificates. there was work to allow custom
verification routines which we could use, but this never finished:
https://github.com/shazow/urllib3/pull/257
so right now, just treat missing socket information as if the cert was
missing.
Closes: #76
=> workaround new limitation in requests

doc/changelog.txt, linkcheck/bookmarks/chrome.py, linkcheck/bookmarks/chromium.py, linkcheck/configuration/__init__.py, linkcheck/logger/blacklist.py, requirements.txt, setup.py
~/.linkchecker is used instead of the xdg equivalents if the directory
exists (backward compatibility).
=> use xdg dirs for config & data

README.rst
In accordance to the review of #89, I've created a commit with only the python 3 compatibility note.
=> Document missing python 3 compatibility; Fixes #88

linkcheck/url.py, tests/checker/data/http.html.result, tests/test_url.py
According to <https://tools.ietf.org/html/rfc3986>:
fragment    = *( pchar / "/" / "?" )
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded = "%" HEXDIG HEXDIG
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
Fixes #96
=> Fix fragment identifier quoting

linkcheck/configuration/__init__.py
See  https://github.com/linkcheck/linkchecker/issues/115 ("linkchecker --version" leads to warning log)
=> Use os.makedirs(...) instead of os.mkdir(...)
=> Do not fail to mkdir ~/.local/share/linkchecker/plugins when ~/.local/share is missing

.travis.yml
Test in Python 3 versions in allow-failures mode (as a prerequisite for porting to porting).
Test on all branches (because it is quite annoying in development process).
=> update .travis.yml to test in Pyhon3 in allow-failures mode

tests/test_parser.py, tox.ini
Separate parser tests, so it is easy to determine which are failing.
=> Execute parser test by parametrized

tests/checker/__init__.py, tests/checker/data/all_parts.html, tests/checker/data/all_parts.html.result, tests/checker/test_all_parts.py
This adds a test for various parts of `url_data` variable in `Logger`.
I am not sure, if this works on all platforms.
=> Test for linenumbers and other parts of url_data

linkcheck/director/aggregator.py, tests/cookies.txt, tests/test_cookies.py
There was some kind of confusion between a module and a function argument, introduced in commit 90257a1b5ed552ba015e74fa40dca052e17d1f38.  As far as I can tell, the `cookies` parameter passed to `new_request_session()` is supposed to be a `cookielib.CookieJar()` instance, which has no `from_file()` method.
Fixes #62.
I would prefer to write a regression test for this before merging.  I'm not sure I'll manage that in a reasonable time interval, and it's probably better to fix the bug without a regression test than to leave the bug unfixed, so, @anarcat, feel free to merge this in a couple of days if there are no indications of progress.
(TBH I would prefer if somebody else wrote a regression test, but I don't think that's likely.)
(FWIW writing about how I'm unlikely to do X is my way of …
=> Fix internal error when using cookies

linkcheck/cookies.py, linkcheck/director/aggregator.py, tests/cookies.txt, tests/test_cookies.py
requests.cookies.merge_cookies() requires a dict or a CookieJar as the second argument.  We've been passing lists of Cookie objects instead.
Fixes #62, harder this time.
=> Load cookies from the --cookiefile correctly

tests/checker/test_http_misc.py
Without this patch, tests would fail on IPv6 hosts with this
mysterious error:
```
_______________________________________________________________________ TestHttpMisc.test_html ________________________________________________________________________
tests/checker/test_http_misc.py:30: in test_html
self.obfuscate_test()
tests/checker/test_http_misc.py:51: in obfuscate_test
url = u"http://%s/" % iputil.obfuscate_ip(ip)
linkcheck/network/iputil.py:290: in obfuscate_ip
raise ValueError('Invalid IP value %r' % ip)
E   ValueError: Invalid IP value '2a02:2e0:3fe:1001:7777:772e:2:85'
```
As it turns out, the test host (`www.heise.de`) does have an IPv6
record and our tests pass on Travis only because they do not have a
working IPv6 stack. I happen to have IPv6 at home and tests are broken
here, …
=> make tests pass on IPv6 hosts

requirements.txt, setup.py
This is already in the code in `linkcheck/__init__.py`, update the requirements and setup file so it can be installed via `pip`.
=> Require requests >= 2.4

CONTRIBUTING.mdwn
While reviewing our contribution guidelines in #139, we found we had no formal way of removing disappeared or idle maintainers, at least not explicitly, in the Membership section. This was a problem to get changes done on the contributing document which requires consensus from the maintainers.
This change introduces a way to make changes to the document by using it as a "vote of confidence", in a way: if a change is proposed and an administrator does not respond within a given 1-month delay, the administrator can be demoted down to a regular maintainer and the document approved.
Closes: #139
=> introduce demotion rules

README.rst
See https://github.com/linkchecker/linkchecker/issues/4#issuecomment-356449159 
I had trouble installing but with `pip install git+https://github.com/linkchecker/linkchecker.git` it is quite easy and at the moment the easiest way imho.
=> Update README to include easy installation instructions for pip

dev-requirements.txt
I was trying to run the unit tests following the guide in `development.mdwn` but ran into some issues. 
Most noticeably it seems that the tests use modules not specified as dependencies. This PR fixes that
I am also seeing: 
```
[gw2] darwin -- Python 2.7.15 /Users/cm/.pyenv/versions/2.7.15/bin/python2.7
self = <tests.checker.test_file.TestFile testMethod=test_unicode_filename>
def test_unicode_filename (self):
>       self.file_test(u"Мошкова.bin")
tests/checker/test_file.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/checker/__init__.py:226: in file_test
self.fail_unicode(msg)
tests/checker/__init__.py:232: in fail_unicode
self.fail(msg)
E   AssertionError: tests/checker/data/???????.bin
E   --- 
E …
```
=> Fix test requirements for Mac OS

requirements.txt, setup.py
Requests versions <= 2.19.1 are vulnerable to CVE-2018-18074:
> The Requests package through 2.19.1 before 2018-09-14 for Python sends
> an HTTP Authorization header to an http URI upon receiving a
> same-hostname https-to-http redirect, which makes it easier for remote
> attackers to discover credentials by sniffing the network.
Thank you, GitHub security alerts, for bringing this to my attention.
I do not recall why we were pinning requests to `< 2.15` and I hope Travis CI will remind me.
=> Require a recent Requests version

requirements.txt, setup.py
PR #196 bumped this to 2.20 to fix a security warning about requests
in our repository, but I believe that warning can be fixed by removing
only the upper bound. This should make backporting linkchecker to
older systems easier, where requests presumably has the 2.20 fix
backported.
=> lower requirements to allow install on older systems

tests/checker/test_http.py, tests/checker/test_http_misc.py, tests/checker/test_http_redirect.py, tests/checker/test_httpbin.py, tests/checker/test_misc.py, tests/checker/test_whitespace.py
I believe all these tests require the network, at least they seem to
fail if it's I run them without connecting my computer to the web.
I'm looking at this as part of packaging linkchecker for GNU Guix,
where the package is build and the tests are run in a isolated
environment, intentionally without network access, to avoid issues
with non-reproducible package builds.
=> Mark more tests that require the network

linkcheck/configuration/__init__.py, linkcheck/logger/blacklist.py
=> {python3_05a} Use Python 3 compatible octal masks

tests/checker/__init__.py
```
self = <tests.checker.test_file.TestFile testMethod=test_good_dir_space>
def test_good_dir_space (self):
...
>       self.direct(url, resultlines, recursionlevel=2)
tests/checker/test_file.py:173:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/checker/__init__.py:260: in direct
self.fail_unicode(text(os.linesep).join(l))
tests/checker/__init__.py:237: in fail_unicode
self.fail(msg)
E   AssertionError: Differences found testing
```
---
Fixes #236
=> Fix TestFile results not always ordered as expected values

linkcheck/log.py
warning() has been the documented method since logging was introduced in
Python 2.3.
--- 
Resolves deprecation warnings.
=> Replace deprecated log.warn

tests/configuration/test_config.py
Expected to be removed when the project moves to Python 3 only.
=> Import str as str_text from builtins when supporting transition

linkcheck/strformat.py
locale.format_string() was introduced in Python 2.5.
=> Replace deprecated locale.format()

tests/test_robotstxt.py
urllib.parse.quote() moved from RFC 2396 to RFC 3986 for quoting URL
strings. “~” is now included in the set of reserved characters.
=> Make TestRobotsTxt Python 3.7 compatible

tests/checker/__init__.py, tests/checker/test_all_parts.py
tests/checker/test_all_parts.py:21: in <module>
import __init__ as init
E   ModuleNotFoundError: No module named '__init__'
testWarning: cannot collect test class 'TestLogger' because it has a
__init__ constructor
=> Make test_all_parts TestLogger import Python 3 compatible

linkcheck/checker/ftpurl.py, tests/checker/ftpserver.py
Two commits to two separate files:
* tests/checker/ftpserver.py - has been skipped for some time because pyftpdlib had changed
* linkcheck/checker/ftpurl.py - for Python 3 compatibility
Wouldn't be much to see from Travis because Python 2.7 passes the test without the second commit (and Python 3 no where near passing with this branch). For reference Python 3 failure on python3 branch without the second commit:
```
_______________________________ TestFtp.test_ftp _______________________________
tests/__init__.py:93: in newfunc
return func(*args, **kwargs)
tests/checker/test_ftp.py:47: in test_ftp
self.direct(url, resultlines)
tests/checker/__init__.py:267: in direct
self.fail_unicode(str_text(os.linesep).join(l))
tests/checker/__init__.py:244: in fail_unicode
self.fail(msg)
E …
```
=> Get FtpServerTest working by updating to current pyftpdlib API

tests/test_dummy.py, tests/test_updater.py
In test_dummy.py bytes import was left over from previous version of the change
In test_updater.py an instance of unicode() was left unchanged.
=> Fix mistakes in changes to test_dummy.py and test_updater.py in 8f4acc31

linkcheck/lc_cgi.py
2.7 docs say:
This function is deprecated in this module. Use urlparse.parse_qs() instead. It is maintained here only for backward compatibility.
=> Replace deprecated cgi.parse_qs

tests/checker/telnetserver.py
Fixes hanging test runs on Python 3.
This is an alternative to #253.  It's actually based on #253, but I'm considering squashing all the changes to one commit because the last commit essentially undoes what the previous commits did and does a completely different thing.
If this one is merged it'll cause conflicts for #254, but those should be easy to resolve.
=> Stop threads more reliably

tests/checker/telnetserver.py
I'm not entirely sure why the test is hanging, but this seems clear
enough:
- the test setup spawns a (non-daemon) background thread that runs
forever, or until it is told to quit by receiving a TCP packet on a
certain port
- the test teardown tries to tell the background thread to quit (which
doesn't work) and waits for that to happen
- as a result the entire test run hangs forever
This commit adds a timeout as an extra safety net so that the test run
will complete even if the clean shutdown procedure fails for some
reason.
=> Fix a hanging test on Python 3

tests/checker/telnetserver.py
Linkchecker's telnet://username:password@host:port URL verification logic is
- connect to host:port
- wait for 'login: ' to appear (with a 10 second timeout), send username
- wait for 'Password: ' to appear (with a 10 second timeout), send password
The test spawns a fake telnet server on localhost that never presented
the login/password prompts, forcing the 10 second timeout three times.
This commit makes the fake telnet server emit the expected prompts,
making the test pass in .2 seconds.
=> Make test_telnet.py fast

linkcheck/strformat.py
branched from python3_18 #228.
=> {python3_18a} Python3: fix strformat ascii_safe() and unicode_safe()

linkcheck/logger/csvlog.py
The CSV buffer is being truncated on each new row, but since the stream's pointer isn't also being reset, each new row starts at the same position as the previous row, but with null bytes up until that point.  This leads to increasing growth in the length of each CSV row, since each line will be padded with null bytes equivalent to the previous row's length.
Here's an explanation of this same issue in a simplified snippet: https://stackoverflow.com/questions/39109068/why-does-truncating-a-bytesio-mess-it-up
I noticed this when a CSV output containing 1,000 rows was 13MB in size, which seemed quite large. As an example of how this can be seen, currently running `linkchecker -r 1 -v -F csv/test.csv https://linkchecker.github.io/linkchecker/man5/linkcheckerrc.5.html` outputs a CSV with the …
=> Fix CSV output containing increasing number of null byte characters

tests/checker/test_http_misc.py
http://www.heise.de/ now does a redirect to HTTPS instead of denying our crawl via robots.txt.
Fixes #269.
=> Fix failing test

.travis.yml
(The tests don't pass yet, see #205.)
=> Add Python 3.7 to the Travis CI build matrix

linkcheck/lc_cgi.py
Could convert to string variable and reuse rather than causing two conversions?
=> Fix errors caused by logging LCFormError exceptions

linkcheck/checker/fileurl.py
urllib.request.urlopen() expects a string or Request object.
=> {python3_33_alt} Python3: fix opening file URLs

linkcheck/checker/httpurl.py
From test_http_redirect:
```
File "linkchecker/linkcheck/checker/httpurl.py", line 323, in read_content
line: buf.write(data)
locals:
buf = <local> <_io.StringIO object at 0x7f8fe2f45e10>
buf.write = <local> <built-in method write of _io.StringIO object at 0x7f8fe2f45e10>
data = <local> b'<a href="newurl.html">Recursive Redirect</a>\n'
TypeError: string argument expected, got 'bytes'
```
---
This is my version of 1a4663b48
=> {python3_39_alt} Python3: fix TypeError in HttpUrl.read_content()

linkcheck/director/console.py
Can't see that this was needed on Python 2. Obviously causes an exception on Python 3.
=> Remove unnecessary unicode() from StatusLogger.writeln()

linkcheck/htmlutil/linkparse.py
Stopped being used with removal of UrlBase.set_title_from_content() in:
7b34be59 ("Introduce check plugins, use Python requests for http/s connections, and some code cleanups and improvements.", 2014-03-01)
---
This is dead code in current master. Needs to go as well because the new parser doesn't support peek().
=> Remove unused linkparse.TitleFinder

linkcheck/bookmarks/opera.py, linkcheck/checker/urlbase.py, linkcheck/director/aggregator.py, linkcheck/parser/__init__.py, linkcheck/plugins/markdowncheck.py, requirements.txt, setup.py
Not for merging yet, it needs reviewing and is based on the other two big branches. As such only the "Commits on Sep 20, 2019" should be considered.
The key change is to decode early in HttpUrl or UrlBase. HttpUrl uses requests to do the decoding, UrlBase tries UTF-8 and if that fails uses Beautiful Soup to detect the encoding.
This would replace #295, #296, #304 and simplify #298.
=> Decode content when retrieved

linkcheck/parser/__init__.py, pytest.ini, tests/checker/__init__.py, tests/checker/data/utf8.html, tests/checker/data/utf8.html.result, tests/checker/test_misc.py, tox.ini
Fix TypeError: string arg required in find_links().
Fixes #317.
=> Fix TypeError: string arg required in find_links()

linkcheck/director/aggregator.py
This fixes a race condition where the main thread would check if any
internal errors happened and get back a 0 while a worker thread was
still busy printing the internal error message before incrementing the
counter.
Fixes #320.
My experiments show that this adds no perceptible delay to the script
runtime (on Linux).  More specifically, there already is an annoying
perceptible delay of about 1 second, but it's not caused by this change.
I thought about adding a regression test for this, but couldn't come up with a way to do it.
=> Wait for threads to exit after stopping them

linkcheck/__init__.py
This code was added in:
efbbb656 ("Remove python-dns conflict by moving the dns module into a custom subdirectory.", 2012-12-07)
Installation of linkcheck_dns stopped with:
0a13fae3 ("remove third party packages and use them as dependency", 2018-01-06)
.
=> Don't add linkcheck_dns directory to sys.path

linkcheck/plugins/parseword.py
MS Word files are binary data, and get_temp_filename() will write them
to disk using open(..., 'wb'), so we want to pass bytes in there, not
Unicode.
See #323.
If anyone has a Windows machine with Word installed and would like to test this code, that would be amazing.
=> Fix MS Word parser, hopefully

tests/checker/test_news.py
pytest output before this change:
SKIPPED [3] tests/__init__.py:217: condition: True
SKIPPED [1] tests/checker/test_news.py:63: condition: True
SKIPPED [1] tests/checker/test_news.py:41: condition: True
SKIPPED [1] tests/checker/test_news.py:116: condition: True
SKIPPED [1] tests/checker/test_news.py:75: condition: True
After:
SKIPPED [3] tests/__init__.py: disabled for now until some stable news server comes up
SKIPPED [4] tests/checker/test_news.py: disabled for now until some stable news server comes up
=> Explain why these tests are being skipped

linkcheck/parser/sitemap.py, tests/checker/data/sitemap.xml.result, tests/checker/test_http_misc.py
PyExpat wants bytes on Python 2.  See #323.
This PR also adds a regression test (by reusing the sitemap.xml we had for mimetype detection tests).
=> Fix sitemap parser

linkcheck/plugins/viruscheck.py, tests/test_clamav.py, tox.ini
This PR also contains the pdfminer fix mentioned in https://github.com/linkchecker/linkchecker/pull/249#issuecomment-546301773 and should, if cherry-picked, allow the tests to pass on that branch.
=> Fix test_clamav.py on Python 3

dev-requirements.txt, tests/checker/httpserver.py, tests/checker/test_https.py, tox.ini
Previously disabled because it was using Amazon. Verification is disabled because we generate our own certificate.
Also use the generated certificate to test httputil.x509_to_dict() and the fix required for Python 3.
=> Enable https checking using a test server

linkcheck/httputil.py
The test was added but not the fix in:
ecd06776 ("Fix TypeError when checking https link and test", 2019-11-11)
Which is caught by the new test when run on Python 3:
```
___________________ TestHttps.test_x509_to_dict__________________
[gw14] linux -- Python 3.6.9 /usr/bin/python3.6
tests/checker/test_https.py:72: in test_x509_to_dict
self.assertEqual(httputil.x509_to_dict(cert)["notAfter"],
linkcheck/httputil.py:47: in x509_to_dict
parsedtime = asn1_generaltime_to_seconds(notAfter)
linkcheck/httputil.py:68: in asn1_generaltime_to_seconds
res = datetime.strptime(timestr, timeformat + 'Z')
E   TypeError: strptime() argument 1 must be str, not bytes
```
=> Actually fix TypeError when checking https link

requirements.txt, setup.py
bs4 is a dummy package managed by the developer of Beautiful Soup to prevent
name squatting. The official name of PyPI’s Beautiful Soup Python package is
beautifulsoup4. The bs4 package ensures that if you type pip install bs4 by
mistake you will end up with Beautiful Soup.
However, for requirements, it's cleaner to use the proper name.
For downstream packaging in Fedora, this avoids the need of packaging
the dummy package.
=> Require beautifulsoup4 instead of bs4

setup.py
The python_requires is the important one; it means once we publish a new release on PyPI, pip install will know not to try to install it if you run it on Python 2 and will fall back to an older version.
=> Declare supported Python versions in setup.py

linkcheck/HtmlParser/__init__.py, linkcheck/HtmlParser/htmlsax.py, tests/htmllib.py, tests/test_parser.py
This change is made because the linkchecker handlers only process Tags.
The test HtmlPrettyPrinter handler is updated to output element text because its support for non-Tag elements has been removed. This results in a number of the existing tests still passing.
---
We can go further than just removing DOCTYPE support.
I've just deleted parsetests strings that were causing failures (for the most part).
We don't have our own HTML parser to test any more, on the other hand it seems worth having a dedicated parser test (we could just leave it to be inferred from the specialist tests). What do you think?
I'll have a look at what is left of the parser and the interface to it. I think there might be some more tidying possible there.
I couldn't resist a Python 2 tidy up as well, hopefully it is …
=> Remove support for non-Tag elements from Parser

linkcheck/bookmarks/chrome.py, linkcheck/bookmarks/chromium.py, linkcheck/bookmarks/firefox.py, linkcheck/bookmarks/opera.py, linkcheck/bookmarks/safari.py, linkcheck/checker/fileurl.py, linkcheck/htmlutil/formsearch.py, linkcheck/strformat.py, tests/test_dummy.py
Several instances for MS Windows left unchanged.
---
The instances in the bookmarks modules can't be part of the existing tests (they haven't been failing under Python 3). They seem simple enough to update, for Linux, not sure about Windows so have left those.
=> Remove use of Python 2 unicode() and related u prefixes

setup.py
Code that can be removed from setup.py because there are no C extensions left or a need to support Python 2.
=> Tidy setup.py for C extensions and Python 2

linkcheck/better_exchook2.py, linkcheck/checker/ftpurl.py, linkcheck/checker/urlbase.py, linkcheck/cmdline.py, linkcheck/configuration/confparse.py, linkcheck/decorators.py, linkcheck/director/console.py, linkcheck/i18n.py, linkcheck/loader.py, linkcheck/logger/html.py, linkcheck/trace.py, requirements.txt, setup.py, tests/__init__.py, tests/test_containers.py, tests/test_dummy.py, tests/test_updater.py, tox.ini
This is the start of the removal of Python 2 code, fixing deprecation warnings and some other accumulated tidying (step 4). There are going to be a number of PRs. To start, some that can be merged to master without interfering with the parser PRs.
=> Remove use of the future package

linkcheck/checker/httpurl.py, linkcheck/htmlutil/htmlsoup.py, linkcheck/htmlutil/linkparse.py, linkcheck/parser/__init__.py, linkcheck/plugins/anchorcheck.py, tests/checker/data/norobots.html, tests/checker/test_content_allows_robots.py, tests/htmllib.py, tests/test_linkparser.py, tests/test_parser.py
This goes after #361.
This is the last of the HTML parser review, replacing MetaRobotsFinder with BeautifulSoup.find() means code can be simplified further with the removal of HTML handlers.
There is more work on the login form searching to try and make it more robust with better logging.
=> Stop using HTML handlers and improve login form error handling

linkcheck/logger/__init__.py
The `__metaclass__` syntax is a Python-2-ism.  It was replaced with
class _Logger (object, metaclass=abc.ABCMeta):
in Python 3.  And then Python 3.4 introduced abc.ABC which is an empty class that has ABCMeta as the metaclass, making it simpler to define abstract base classes.
=> Make _Logger an abstract base class

Dockerfile, README.rst
It is my understanding that Python 3 is now supported.
The current Dockerfile, based on python:2 no longer builds, and fails with this error:
Running command git clone -q https://github.com/linkchecker/linkchecker.git /tmp/pip-req-build-l0YhGn
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-l0YhGn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-l0YhGn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-l0YhGn/pip-egg-info
cwd: /tmp/pip-req-build-l0YhGn/
Complete output (1 lines):
This program requires Python 3.5 or later. …
=> Update README and Dockerfile with Python 3

tests/checker/cgi-bin/input2cookies.py, tests/checker/data/loginform.html, tests/checker/httpserver.py, tests/checker/test_loginurl.py
A new cgi-bin directory is created to identify the scripts to be run by
http.server.CGIHTTPRequestHandler.
---
Adds coverage for director.aggregator.Aggregate.visit_loginurl(). Can be extended to support user or password only testing.
=> Add test for loginurl

linkcheck/director/aggregator.py, linkcheck/htmlutil/loginformsearch.py, tests/checker/data/loginform_password.html, tests/checker/data/loginform_user.html, tests/checker/test_loginurl.py
This is based on #364 only the last commit is new.
An idea of how login forms with usernames or passwords only could be supported. But - I think more understanding of how the related code works and tests required.
=> Support login forms with user and/or password

linkcheck/checker/__init__.py, linkcheck/checker/fileurl.py, linkcheck/checker/mailtourl.py, linkcheck/checker/proxysupport.py, linkcheck/checker/urlbase.py, linkcheck/configuration/__init__.py, linkcheck/director/aggregator.py, linkcheck/lc_cgi.py, linkcheck/logger/html.py, linkcheck/plugins/anchorcheck.py, linkcheck/robotparser2.py, linkcheck/strformat.py, linkcheck/url.py, scripts/analyze_memdump.py, tests/checker/httpserver.py, tests/test_cgi.py
Only two commits, and the second one overlaps the first, but the overlaps are only html_escape -> html.escape - I think that change is worth it to make it clear we are using the standard function and not our own.
I do recommend the split diff view for these.
=> Make urllib imports and html.escape Python 3 only

linkcheck/updater.py, setup.py
It is confusing to have different versions of the code self-identify
with the same version number.  In my experience it's always best to
increment the version number and add a .dev0 suffix right after making a
release.  When it's time to make a new release, you remove the .dev0,
commit, tag that commit, then make second commit that bumps the version
and adds .dev0 back.
This way only releases identify themselves as "version X.Y.Z" with no
.dev0 suffix and it's immediatelly apparent when you've got a prerelease
installed from git.
=> Bump version in git to 10.0.0.dev0

linkcheck/checker/fileurl.py, linkcheck/checker/itmsservicesurl.py, linkcheck/checker/urlbase.py, linkcheck/fileutil.py, linkcheck/htmlutil/linkparse.py, linkcheck/lc_cgi.py, linkcheck/logger/__init__.py, linkcheck/logger/customxml.py, linkcheck/logger/text.py, linkcheck/plugins/markdowncheck.py, linkcheck/plugins/parsepdf.py, linkcheck/strformat.py, linkcheck/url.py, tests/__init__.py, tests/checker/__init__.py, tests/configuration/test_config.py
These were used in the conversion to Python 3 to support both Python 2 and 3.
I've been fairly cautious (I hope) in the balance between removing instances of str_text and replacing with str. It may be possible to remove more after closer analysis, they can still be found by searching for isinstance.
=> Remove "from builtins import str as str_text"

linkcheck/checker/urlbase.py, tests/checker/data/empty.html.result, tests/checker/test_file.py
When BeautifulSoup finds an empty file on disk, it sets original_encoding to None.  It doesn't matter what encoding we pick for empty files, so let's just pick one.
I don't know if there are any circumstances where BeautifulSoup might set the encoding to None for a non-empty file.
Closes #392.
=> Fix internal error on empty HTML files

linkcheck/cache/robots_txt.py, linkcheck/checker/httpurl.py, linkcheck/robotparser2.py
Maybe closes #396?
I'm setting the timeout in the robot parser fetching code.  I can attach with gdb and see the timeout:
```
#69 Frame 0x7fea5052bcf0, for file /home/mg/.local/pipx/venvs/LinkChecker/lib/python3.8/site-packages/requests/sessions.py, line 1298, in request (self=<Session(headers=<CaseInsensitiveDict(_store={'user-agent': ('User-Agent', 'Mozilla/5.0 (compatible; LinkChecker/10.0.0.dev0; +https://linkchecker.github.io/linkchecker/)'), 'accept-encoding': ('Accept-Encoding', 'gzip, deflate'), 'accept': ('Accept', '*/*'), 'connection': ('Connection', 'keep-alive')}) at remote 0x7fea64170550>, auth=None, proxies={}, hooks={'response': []}, params={}, stream=False, verify=True, cert=None, max_redirects=10, trust_env=True, …
```
=> Make sure fetching robots.txt uses the configured timeout

linkcheck/checker/httpurl.py, linkcheck/checker/urlbase.py, tests/checker/data/http_empty.html.result, tests/checker/test_http.py
This is the http version of issue #392. HttpUrl has it's own get_content() with a decode() (a hint at the possible fix). Let's just check this does cause an error.
Fixes #392.
=> Fix internal error on empty HTML files accessed over HTTP

linkcheck/better_exchook2.py, linkcheck/bookmarks/chrome.py, linkcheck/bookmarks/chromium.py, linkcheck/bookmarks/firefox.py, linkcheck/bookmarks/opera.py, tests/checker/test_file.py
Instances in MS Windows specific code still need to be fixed. Mark to be
ignored by flake8, find with:
flake8 --disable-noqa --select=F821
=> Remove instances of Python 2 unicode

.gitignore, .travis.yml, MANIFEST.in, Makefile, setup.cfg, setup.py, tox.ini
This PR
- gets rid of the `MANIFEST` file generated by custom build commands in setup.py and the Makefile
- updates MANIFEST.in to include ALL THE FILES!
- adds check-manifest to CI so we can be sure MANIFEST.in will always include ALL THE FILES!
Closes #414.
=> Include all files in the sdist via MANIFEST.in

tests/checker/test_file.py, tests/checker/test_http.py, tests/checker/test_https.py
Nice to enable some tests without the internet, important to mark one that can't:
Subject: Mark TestFile.test_html_url_quote as need_network
Else without the internet the test fails, eventually, with:
warning No MX mail host for users.sourceforge.net found
=> Adjust tests for need_network

doc/changelog.txt, linkchecker
These options were replaced by plugins in:
7b34be59 ("Introduce check plugins, use Python requests for http/s
connections, and some code cleanups and improvements.", 2014-03-01)
Released in 9.0.
=> Remove ineffective command-line options

linkcheck/bookmarks/chrome.py, linkcheck/checker/__init__.py, linkcheck/parser/__init__.py, setup.cfg, tox.ini
- Prevent "F821 undefined name" being caused by gettext prefixes
- Include the main executable when running flake8 from the top directory
without specifying files
---
Minimal .flake8 to support running flake8 on its own when developing, and always avoid the F821s from gettext. Leaving specifying the objects to be checked by tox means the stand-alone use behaves as the developer expects. Add checking the main linkchecker executable from tox.
=> Update setup.cfg flake8 section

doc/examples/filter_xml_output.py, doc/web/hooks/__hooks__.py, scripts/analyze_memdump.py, scripts/removeafter.py, scripts/update_iana_uri_schemes.py, scripts/viewprof.py, setup.cfg, tox.ini
This enables flake8 for everything and gets the violations from doc/ and scripts/ out of the way, including a first small-scale test of black.
N.B. it does set max-line-length to 88 as recommended by Black, I'll let them explain:
https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length
Plenty to ponder there, possibly easier with this concrete example.
=> Resolve flake8 violations in doc/ and scripts/ and enable checking of all files

linkcheck/bookmarks/chrome.py
```
>>> from xdg import xdg_config_home
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'xdg_config_home' from 'xdg' (/usr/lib/python3.7/site-packages/xdg/__init__.py)
```
Fix taken from the other bookmarks files.
This file isn't actually used by linkchecker, fix in case it saves anyone time in future.
=> Fix xdg_config_home import in bookmarks/chrome.py

setup.cfg
The Python files under build/ are mere copies, not worth checking.
_LinkChecker_configdata.py is a generated file, not stored in the VCS,
not really part of the source.
=> Tell flake8 to ignore files that should not be checked

doc/de.po, doc/de/linkchecker.1, doc/de/linkcheckerrc.5, doc/linkchecker.doc.pot, doc/translations.md, linkcheck/plugins/markdowncheck.py, po/Makefile
Changes to man page format in:
a205a372 ("Update man pages to optimise for both html and man", 2020-04-24)
broke the mapping in doc/de.po, so update the .pot and de.po and then move existing German strings and regenerate the de man pages.
Also some fixes for the application translation generation and a basic explanation of the use of make in a new document translations.md.
=> Update man page translation and fixes for application translation process

linkcheck/checker/fileurl.py, linkcheck/checker/mailtourl.py, linkcheck/configuration/confparse.py, linkcheck/logger/blacklist.py, linkcheck/logger/dot.py, linkcheck/logger/html.py, linkcheck/logger/sitemapxml.py, linkcheck/plugins/locationinfo.py, linkcheck/plugins/syntaxchecks.py, setup.py, tests/checker/__init__.py, tests/test_po.py
Various review comments from #439 and before.
Plus use python3 in setup.py. I think this might save some reports  similar to issues we have seen - avoid an error for an Ubuntu 20.04 user with Python 2 installed who runs `./setup.py`.
=> Assorted review comments and use python3 for setup.py

doc/changelog.txt, doc/de.po, doc/de/linkchecker.1, doc/en/linkchecker.1, doc/install.txt, doc/linkchecker.doc.pot, doc/web/media/man1/linkchecker.1.html, linkcheck/configuration/__init__.py, linkchecker, setup.py
GConf is replaced by dconf and the GSettings API in GNOME 3.
---
I don't have a proxy setup, but the code being replaced definitely won't work.
=> Update GNOME proxy support for GNOME 3 and Python 3

doc/install.txt
py2app support was removed in:
e3ab902 ("Remove platform-specific installer stuff and ensure a build
.whl wheel file can be built.", 2016-01-17)
---
The instructions do not work as reported in #446 and cannot because the support for pyapp and the app Makefile target were removed with wheels as the intended replacement.
Also a commit to build universal wheels only.
=> Remove manual setup for OSX from install instructions

doc/install.txt
The first release of macOS was in 2016.
=> Update Mac installation instructions with Homebrew pip and macOS

linkcheck/configuration/__init__.py
KDE 3 was superseded in 2008.
KDE 4 uses: ${HOME}/.kde4/share/config/kioslaverc
KDE 5 (Kubuntu) uses: ${HOME}/.config/kioslaverc
Default ReversedException is false
=> Replace KDE 3 proxy support with KDE 5 support

linkcheck/cache/urlqueue.py
Skipping introduced in:
eaa538c8 ("don't check one url multiple times", 2016-11-09)
=> Log a debug message when a cached URL is skipped

doc/web/content/faq.md
Options removed in 8.5:
64d95e45 ("Remove local HTML and CSS syntax check.", 2013-02-08)
Plugins added in 9.0:
7b34be59 ("Introduce check plugins, use Python requests for http/s
connections, and some code cleanups and improvements.", 2014-03-01)
=> Update the FAQ with plugins for HTML and CSS syntax checking

linkcheck/lc_cgi.py, tests/test_cgi.py
Only called from application() with arguments. Causes local environment
to be embedded in documentation when using Sphinx autodoc.
=> Remove defaults from lc_cgi.checklink()

linkcheck/configuration/__init__.py, linkchecker
- Set the correct default for the setting in configuration.Configuration
- Detect when the argument is not passed by setting the default to None
(store_false sets the default to True)
---
Closes #52
=> Fix status=0 setting being ignored

linkcheck/checker/const.py
e.g.:
`<a href="http://localhost]">square</a>`
---
Closes #43.
=> Fix critical exception when parsing a URL with a ]

Makefile
Not sure if this file is still being used, but noticed it still pointed to a python version that no longer builds
=> Update Makefile to use python3

linkcheck/logger/blacklist.py
A second run creates an additional entry in blacklist rather than
upating the original:
1 '"(\'http://localhost/broken.html\', \'http://localhost/nosuchlink.html\')"'
1 "('http://localhost/broken.html', 'http://localhost/nosuchlink.html')"
Broken since at least 9.3:
1 "(u'http://localhost/broken.html', u'http://localhost/nosuchlink.html')"
1 u'"(u\'http://localhost/broken.html\', u\'http://localhost/nosuchlink.html\')"'
If such an entry is found LinkChecker will now halt. Either remove
the entry or the whole file.
=> Fix blacklist updating

linkcheck/checker/httpurl.py, linkcheck/checker/urlbase.py, linkcheck/url.py, tests/checker/test_build_url.py
Second attempt, closes #384 
This time with a new test, exception catching (d5690203fc is probably a new backstop here too) and using the same approach as urllib.parse._split functions in places.
=> Replace deprecated urllib.parse.split functions

linkcheck/checker/urlbase.py, tests/checker/data/http_anchor.html, tests/checker/data/http_anchor.html.result, tests/checker/test_anchor.py
Query and fragment URL parts for filesystem URLs are ignored, therefore
test over http.
---
First a new test, let's see it fail.
Closes #460.
=> Fix anchor checking

doc/examples/windows.bat, linkcheck/checker/fileurl.py, tests/checker/test_noproxy.py
os.path.splitunc() removed in Python 3.7.
https://docs.python.org/3/whatsnew/3.7.html#api-and-feature-removals
=> MS Windows Python 3.7 and MS Store compatibility

.travis.yml, doc/Makefile, doc/documentation.md
`make -C doc check` to check the man pages was already present, I switched it to use mandoc - I could have documented why better, man-db was outputting warnings which it wasn't possible to do anything about. Maybe the whole idea of the check is a bit redundant now that they are being generated for us, but it doesn't cost much.
I put the whole check in Travis, as well as mandoc it does use the graphviz deb.
=> Document and test Sphinx documentation

doc/man/de/linkcheckerrc.5, doc/man/en/linkcheckerrc.5, doc/src/man/linkcheckerrc.rst
```
$ grep -rn aborttimeout linkcheck
linkcheck/configuration/confparse.py:167:        self.read_int_option(section, "aborttimeout", min=1)
linkcheck/configuration/__init__.py:184:        self["aborttimeout"] = 300
linkcheck/director/aggregator.py:173:            timeout=strformat.strduration_long(self.config["aborttimeout"]),
linkcheck/director/aggregator.py:200:        timeout = self.config["aborttimeout"]
config["aborttimeout"] is only set from aborttimeout and is the only
value used by Aggregate.abort().
```
---
First some missed multiline hyperlinks in German linkcheckerrc(5) from previous commit.
=> Correct documentation of aborttimeout, no matching option

.github/workflows/publish-pages.yml, doc/documentation.md
To save the separate PRs for gh-pages with massive diffs.
Uses https://github.com/peaceiris/actions-gh-pages to do the publishing.
=> Automatically publish documentation on GitHub Pages

.github/workflows/publish-pages.yml, doc/documentation.md
This gives the Action full control of the branch, it will wipe out anything else e.g. the .gitignore (that isn't needed though if not building in the same repository).
Before merging this I will push a manual commit to gh-pages moving the existing files to root, and point the GitHub pages to the root directory in the project configuration.
=> Publish documentation to the root of gh-pages

Makefile, doc/changelog.txt, linkcheck/bookmarks/safari.py, tests/__init__.py, tests/checker/test_bookmarks.py, tox.ini
plistlib has supported binary files since Python 3.4.
---
Didn't spot this myself first time, but fortunately a comment was added to the Bitbucket bug.
`test_safari_bookmarks_binary` works with plistlib.
=> Stop using biplist

README.rst
...instead of the now seemingly obsolete Travis CI one.
=> Link Github action badge in README.rst

tests/test_parser.py, tox.ini
Beautiful Soup uses chardet, if installed, to detect character
encodings. This can lead to different test results based on whether
chardet is installed or not.
Requests < 2.26.0 requires chardet, but since 2.26.0 Requests requires
charset_normalizer.
Explicitly installing chardet maintains consistent test results.
====
Testing for the first time here. Let's see if it closes #547.
=> Ensure chardet is installed when testing using tox

doc/src/_templates/layout.html, doc/src/index.rst
Reference GitHub Actions instead of Travis in documentation
GitHub Actions refers to itself as singular, at least some of the time.
---
Use an HTML list for custom menu entries in documentation
For compatibility with sphinx_rtd_theme 1.0, which otherwise renders the
entries with buttons.
=> Update documentation with GitHub Actions and prepare for sphinx_rtd_theme 1.0

README.rst, doc/src/index.rst, doc/src/man/linkchecker.rst, doc/src/man/linkcheckerrc.rst, linkcheck/plugins/anchorcheck.py, tests/checker/test_anchor.py
Can't be relied on. Multiple reports of expected results not returned.
https://github.com/linkchecker/linkchecker/issues/542
https://github.com/linkchecker/linkchecker/issues/555
https://github.com/linkchecker/linkchecker/issues/568
Previously a fix was needed just to get the tests working:
0912e8a2c ("Don't strip the URL fragment from cache key if using AnchorCheck", 2020-07-27)
After:
eaa538c81 ("don't check one url multiple times", 2016-11-09)
=> Disable AnchorCheck plugin

config/linkcheckerrc, doc/src/man/linkchecker.rst, doc/src/man/linkcheckerrc.rst, linkcheck/configuration/confparse.py, linkchecker
Mainly documentation, but also make quiet/-q silence INFO messages, including "Checking intern URLs only".
=> Improve output documentation and make quiet/-q set log level to warning

linkcheck/checker/httpurl.py
ISO-8859-1 is a fallback for Requests and causes us to mangle UTF-8
content.
Requests' utils.py:
```py
def get_encoding_from_headers(headers):
"""Returns encodings from given HTTP Header Dict.
:param headers: dictionary to extract encoding from.
:rtype: str
"""
content_type = headers.get('content-type')
if not content_type:
return None
content_type, params = _parse_content_type_header(content_type)
if 'charset' in params:
return params['charset'].strip("'\"")
if 'text' in content_type:
return 'ISO-8859-1'
if 'application/json' in content_type:
return 'utf-8'
```
=> Ignore an encoding of ISO-8859-1 returned by Requests

.github/workflows/publish-pages.yml
`0.0.post1+g2bc0b71`
(And some security work for the publish Pages action).
=> Fix LinkChecker version shown on github.io

linkcheck/htmlutil/linkparse.py, tests/test_linkparser.py
I changed a few things in regards to handling link tags, in particular `dns-prefetch` and `preconnect`.
* `rel` attribute can have multiple values, separated by a space, so switched to substring comparison
* `preconnect` usually uses the root URL (eg `https://fonts.googleapis.com`) for setting up a connection, but that URL can return a 404 in some cases, resulting in a false positive. I changed it to a DNS check for now. This could be changed in the future to use a check for a valid http connection.
I added some tests, too :)
=> Better handling for link rel dns-prefetch and preconnect

linkcheck/robotparser2.py
Match the Python standard library and Google's interpretation:
https://developers.google.com/search/docs/advanced/robots/robots_txt#file-format
Avoid Unhandled LookupError.
=> Assume robots.txt is UTF-8

tests/checker/test_file.py
Closes #16. Old LinkChecker 9 report. Assume it was fixed during the switch to Python 3.
=> Require test_directory_listing to succeed

po/Makefile
Removed in:
5fef9a3b ("Generate linkchecker command using an entry point", 2021-12-20)
=> Remove linkchecker from POSOURCES

Dockerfile, doc/install.txt, setup.py, tests/test_parser.py, tox.ini
Remove cchardet from Docker image, tox env and recommendation
Beautiful Soup 4.11 will use charset-normalizer.
----
Remove PyOxidizer workaround
Not needed with PyOxidizer >= 0.20.0.
---
No runtime changes.
=> Latest PyOxidizer and Beautiful Soup allow workarounds to be removed

dev-requirements.txt, doc/src/man/linkcheckerrc.rst, linkcheck/plugins/parseword.py, tox.ini
pdfminer is no longer actively maintained; distributions are now
packaging pdfminer.six as pdfminer.
=> Test and recommend pdfminer.six for PdfParser

.github/workflows/build.yml
We don't care if the signatures are stale (we only need the EICAR virus test signature), so run freshclam only if the cache is missing entirely.
Closes #709.
Also, use apt-get instead of apt to avoid
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
=> Cache ClamAV signatures

.github/workflows/build.yml
Fixes the check-python-versions job in CI.
=> Python 3.12 final is out, stop using -dev

linkcheck/ansicolor.py, linkcheck/plugins/locationinfo.py
The errors were
************* Module linkcheck.ansicolor
linkcheck/ansicolor.py:190:21: E0606: Possibly using variable 'WinColor' before assignment (possibly-used-before-assignment)
************* Module linkcheck.plugins.locationinfo
linkcheck/plugins/locationinfo.py:107:12: E0606: Possibly using variable 'geoip_error' before assignment (possibly-used-before-assignment)
and while it's true that the variables (WinColor, geoip_error) are assigned conditionally, their use is protected (indirectly) by the same conditionals.
=> Fix pylint errors (false positives)
