- README.rst
> Fix Travis badge in README

- linkcheck/htmlutil/linkparse.py
- tests/checker/test_http.py
> Crawl HTML attributes in deterministic order

- dev-requirements.txt
- requirements.txt
> Move dev requirements into dev-requirements.txt

- .travis.yml
- tox.ini
This repo must be enabled on Coveralls
> report coverate to Coveralls

- doc/install.txt
Pending a resolution to https://github.com/linkcheck/linkchecker/issues/60 
(re-rolling this PR here https://github.com/wummel/linkchecker/pull/640 )
> Remove reference to non existent .dmg file

- linkcheck/htmlutil/formsearch.py
first reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847208
> fix incorrect call to the logging module (Closes: #847208)

- setup.py
Fixes #102.
To clarify: this will not help people using `pip install linkchecker` (even if we get PyPI access), but it should help people running `python setup.py install`, such as some distro packages (AUR).
> Install .mo files correctly

- linkcheck/bookmarks/safari.py
- linkcheck/checker/proxysupport.py
- linkcheck/configuration/__init__.py
- linkcheck/configuration/confparse.py
- linkcheck/cookies.py
- linkcheck/director/__init__.py
- linkcheck/director/aggregator.py
- linkcheck/director/logger.py
- linkcheck/director/task.py
- linkcheck/gzip2.py
- linkcheck/robotparser2.py
- linkcheck/url.py
- tests/__init__.py
- tests/test_po.py
This is set of Python 3 compatibility changes.
It is the easiest changes - syntax and imports mostly.
> Add Python3 support - easiest changes

- Dockerfile
- README.rst
Dockerfile fix, Documentation updated
> Dockerfile fix, Documentation updated

- doc/web/content/faq.md
- doc/web/content/index.md
- doc/web/templates/default.html
point to the new orga at least while we figure out namespace issues
Closes: #112
> replace old links on website

- README.rst
Clarify that we don't have good Windows support directly in the README in a naive hope to reduce the number of duplicates.
Closes: #124
See: #53
> add note about missing Windows support

- CONTRIBUTING.mdwn
> Basic typo correction

- linkcheck/checker/unknownurl.py
Fixes https://github.com/wummel/linkchecker/issues/595
> Added whatsapp:// to ignored protocols

- linkcheck/cache/urlqueue.py
- linkcheck/parser/__init__.py
Portion from #194 which is trivial and independent from that one which might take longer to fixup properly.
> Mutex around parse

- CONTRIBUTING.mdwn
- README.rst
Thank you for developing great tool.  
I added link to files on repository into documents. Could you please review?
> Add link to files on repository into documents

- tests/test_decorators.py
> {python3_05c} Python3: fix logging

- tests/test_containers.py
> {python3_05b} Python3: replace xrange

- linkcheck/bookmarks/firefox.py
- linkcheck/mimeutil.py
DeprecationWarning: Flags not at the start of the expression
> Replace deprecated regexp flags not at start

- linkcheck/i18n.py
This is a alternative fix I suggested in the comments on PR #273.
> Fix test_console.py on Python 3

- linkcheck/cookies.py
```
>       fp = BytesIO(strheader)
E       TypeError: a bytes-like object is required, not 'str'
linkcheck/cookies.py:61: TypeError
```
The email package provides the message_from_string() convenience
function which avoids the need to create a file-like object.
Indeed http.client.HTTPMessage is implemented using email.message.Message.
> {python3_37_alt} Python3: fix TypeError when parsing cookie data

- linkcheck/checker/__init__.py
- linkcheck/lc_cgi.py
- linkcheck/logger/html.py
- scripts/analyze_memdump.py
- tests/checker/httpserver.py
html provided for Python 2 by future
https://python-future.org/compatible_idioms.html#html-escaping-and-entities
> Replace deprecated cgi.escape

- linkcheck/bookmarks/chromium.py
- linkcheck/checker/__init__.py
- linkcheck/checker/fileurl.py
- linkcheck/checker/mailtourl.py
- linkcheck/htmlutil/linkname.py
- linkcheck/htmlutil/linkparse.py
- linkcheck/url.py
Another preparatory PR to separate out commits before the big switch to bs4.
> Revert Python 3 patches not needed after decode

- .travis.yml
- tests/test_clamav.py
Let's see if they pass!
I've seen [other people use clamav-daemon in Travis CI jobs](https://github.com/viper-framework/viper/blob/master/.travis.yml), so it might just work!
> Enable ClamAV integration tests on Travis CI

- linkcheck/checker/httpurl.py
- tests/checker/data/http_utf8.html
- tests/checker/data/http_utf8.html.result
- tests/checker/test_http.py
> Fix TypeError: string arg required in content_allows_robots()

- dev-requirements.txt
- linkcheck/plugins/parsepdf.py
- tox.ini
Inspired by https://github.com/linkchecker/linkchecker/issues/317#issuecomment-544536320 and #323.
Let's see how the tests go.
> Add pdfminer to tox.ini and dev-requirements.txt to enable pdf test

- README.rst
Signed-off-by: Jon Oster <jon.oster@here.com>
> Add instructions to install current release tag from git via pip

- linkcheck/plugins/parsepdf.py
basestring is not available in Python 3. Ensure all URLs are Unicode.
url_data.get_raw_content() is returning bytes.
> Make PdfParser Python 3 compatible

- linkcheck/parser/sitemap.py
- tests/checker/data/sitemap.xml
- tests/checker/data/sitemap.xml.result
URLs within a sitemap file were not being captured.
> Fix XmlTagUrlParser and make Python 3 compatible

- tests/checker/__init__.py
Some url lines were missing a url prefix while others had a double url prefix. diff was reporting more url lines as changed than actually had. Improve formatting by removing newlines from control lines and adding headings.
Before:
```
E   AssertionError: http://localhost:46031/tests/checker/data/sitemap.xml
E   ---
E
E   +++
E
E   @@ -1,4 +1,8 @@
E
E   -url http://localhost:46031/tests/checker/data/sitemap.xml
E   +http://www.example.com/
E   +cache key http://www.example.com/
E   +real url http://www.example.com/
E   +valid
E   +url url http://localhost:46031/tests/checker/data/sitemap.xml
E    cache key http://localhost:46031/tests/checker/data/sitemap.xml
E    real url http://localhost:46031/tests/checker/data/sitemap.xml
E    valid
```
After:
```
E   AssertionError: …
```
> Improve test failure diff

- MANIFEST.in
- linkcheck/bookmarks/safari.py
- linkcheck/configuration/__init__.py
- linkcheck/decorators.py
- linkcheck/fileutil.py
- linkcheck/network/iputil.py
- setup.py
- tests/__init__.py
To merge only once Python 3 only and based on #249.
> Replace memoized with functools.lru_cache and deprecations

- linkcheck/htmlutil/formsearch.py
- tests/test_formsearch.py
Just as well, this has been broken since 51a06d8a. Also commits to fix that and a problem message character.
> Add a test for search_form

- linkcheck/HtmlParser/htmlsax.py
- linkcheck/checker/httpurl.py
- linkcheck/checker/urlbase.py
- linkcheck/htmlutil/formsearch.py
- linkcheck/htmlutil/linkparse.py
- linkcheck/parser/__init__.py
- tests/htmllib.py
- tests/test_linkparser.py
- tests/test_parser.py
This is the remaining work on the parser. The main idea is to replace the Parser class and its recursive method with a function that used the find_all method of a BeautifulSoup object.
I've tried to break it down into a set of commits that explains how we get there. Do suggest any improvements.
> Simplify the Parser class

- linkcheck/htmlutil/linkparse.py
- linkcheck/parser/__init__.py
Should fix #372.
I would like to add a regression test for this before merging to master.
> SWF files are binary data

- linkcheck/__init__.py
- linkchecker
- setup.py
Back to the list of tidy ups, mainly removing Python 2 code.
There are quite a few so if we did them individually we would be here quite a while. I'm trying to group them into themes of a small number of commits that don't overlap. Let me know if it doesn't work and there are too many (or too few...)
> linkchecker and setup.py tidy up

- linkcheck/checker/ftpurl.py
- linkcheck/configuration/confparse.py
- linkcheck/cookies.py
- linkcheck/director/__init__.py
- linkcheck/director/aggregator.py
- linkcheck/director/logger.py
- linkcheck/director/task.py
- linkcheck/log.py
- linkcheck/logger/csvlog.py
- tests/checker/test_noproxy.py
- tests/test_decorators.py
Just a set of Python 2 imports being removed.
> Remove Python 2 imports

- linkcheck/i18n.py
- linkcheck/logger/__init__.py
- linkcheck/logger/csvlog.py
- linkcheck/parser/sitemap.py
- tests/checker/__init__.py
A selection of Unicode conversions that are no longer required.
> Remove Python 2 Unicode string conversions

- linkcheck/plugins/viruscheck.py
- tests/checker/test_viruscheck.py
An attempt to write a test to allow #329 to be merged. Let's see what happens (I haven't tested this).
> Add a test for VirusCheck

- tests/checker/test_content_allows_robots.py
- tests/checker/test_http.py
- tests/checker/test_http_redirect.py
- tests/test_po.py
- tests/test_strformat.py
One extra bit of testing for sitemap indexes, otherwise all minor tidying.
> Assorted test tidy-ups

- linkcheck/fileutil.py
~~Command-line options were replaced by plugins in:~~
~~7b34be59 ("Introduce check plugins, use Python requests for http/s
connections, and some code cleanups and improvements.", 2014-03-01)~~
~~Released in 9.0.~~
> Remove unused code from linkcheck/fileutil.py

- .travis.yml
- setup.cfg
- tox.ini
> Add a 'tox -e flake8' and a Travis CI job

- linkcheck/director/checker.py
- linkcheck/director/interrupt.py
- linkcheck/director/status.py
- tests/checker/__init__.py
That's the last of the commits I had collected.
The middle one does improve the logging output, where bytes were being output.
> Remove encoding of TestLogger diff  and url in Checker.check_url_data()

- doc/install.txt
> do not require ssh to clone from source

- linkcheck/director/aggregator.py
Also add a couple of XXX comments about using proxy and possibly disabling TLS certificate checking.
The lack of timeout was discovered while studying bug #396, but this is an independent bug.
OTOH with this PR and #408 we should be sure all HTTP fetches use timeouts.
I have not looked at timeout handling in other protocol support, and I don't intend to at the moment. 
There are no tests.  I'm not sure how to test this.
> Make sure login form fetching uses a timeout and sends User-Agent

- README.rst
(Also change some HTTP URLs to HTTPS).
I think this is the minimum fix we should do ASAP to avoid [user confusion](https://github.com/linkchecker/linkchecker/issues/88#issuecomment-633853033), while we hash out all the questions raised in the discussion in #362.
> Fix misleading information in the README

- linkcheck/__init__.py
- linkcheck/better_exchook2.py
- linkcheck/checker/httpurl.py
- linkcheck/colorama.py
- linkcheck/configuration/__init__.py
- linkcheck/fileutil.py
- linkcheck/parser/__init__.py
- linkcheck/strformat.py
A mix of unused or out of date code and some simple line moves to resolve E402 and F401 violations.
> Resolve flake8 import related violations

- tests/checker/data/sitemapindex.xml
- tests/checker/data/sitemapindex.xml.result
- tests/checker/test_http_misc.py
Update sitemap.xml so that this test can work without the network.
> Add coverage for parser.sitemap.parse_sitemapindex()

- linkchecker
- setup.py
black does some interesting thing to setup.py.
> Resolve flake8 violations in linkchecker and setup.py

- linkcheck/strformat.py
- tests/test_strformat.py
Some more unused code, saves a couple of imports.
> Remove unused code from strformat.py

- config/linkcheckerrc
- doc/en/linkcheckerrc.5
- doc/web/media/man5/linkcheckerrc.5.html
- linkcheck/configuration/__init__.py
- linkcheck/director/__init__.py
- linkcheck/htmlutil/loginformsearch.py
Manual and log message changes to hopefully explain this better to users.
> Improve documentation of authentication

- .travis.yml
- linkcheck/checker/__init__.py
- linkcheck/checker/httpurl.py
- linkcheck/checker/internpaturl.py
- linkcheck/checker/urlbase.py
- linkcheck/logger/csvlog.py
- linkcheck/plugins/locationinfo.py
- linkcheck/plugins/parsepdf.py
- linkcheck/strformat.py
- tests/__init__.py
- tests/test_locationinfo.py
- tests/test_strformat.py
- tox.ini
I don't have the energy to check each use individually - this is following the rip it out and fix the tests approach.
What do you think?
> Remove strformat.unicode_safe()

- linkcheck/checker/fileurl.py
- linkcheck/fileutil.py
- linkcheck/robotparser2.py
- linkcheck/strformat.py
- linkcheck/url.py
More info in the comments.
The one for FtpUrl looks like a fix.
> Remove or replace uses of isinstance()

- linkcheck/logger/csvlog.py
> Fix CSV logger not recognising base part setting

- linkcheck/htmlutil/linkparse.py
> Fix problems with trailing commas and data: URIs in srcset values

- linkcheck/checker/unknownurl.py
- scripts/removeafter.py
- scripts/update_iana_uri_schemes.py
- setup.cfg
> Update IANA scripts and ignored schemes

- linkcheck/mimeutil.py
- tests/checker/data/no_decl_sitemap.xml
- tests/checker/data/no_decl_sitemapindex.xml
- tests/test_mimeutil.py
> Detect sitemaps that do not start with an XML declaration

- linkcheck/loader.py
Closes  #334
No automated test but I have tested this manually.
> Fix deprecation warning for use of the imp module

- linkcheck/url.py
- tests/test_url.py
Resolve some deprecations warnings for urllib.parse.split{host,type}() too.
> Remove unused code from url.py

- README.rst
- dev-requirements.txt
- doc/install.txt
- doc/src/conf.py
- doc/src/man/linkcheckerrc.rst
- linkcheck/configuration/__init__.py
- setup.py
Tweaks to documentation and a copyright update. (Plus drop py2app from dev-requirements.txt)
> Documentation Updates

- Dockerfile
Currently reduces image size from 896MB to 126MB.
> Use Python:3-slim base image in Dockerfile

- linkcheck/configuration/__init__.py
- linkcheck/logger/text.py
- linkchecker
Tidy intro, update http links and replace from linkcheck.
> Tidy linkchecker

- doc/changelog.txt
- setup.py
My suggestions for updating the changelog. And update the version.
> Update changelog and version

- doc/src/index.rst
Oops... I didn't use the automated links because some pages are includes of other files, and the code pages are generated.
> Fix the edit link for the web site front page

- .github/workflows/build.yml
- tests/test_clamav.py
- tox.ini
Also add tox -e check-python-versions because it was low-hanging fruit and I wanted to be sure.
> Convert .travis.yml to GitHub Actions

- config/linkcheckerrc
- doc/man/de/linkchecker.1
- doc/man/de/linkcheckerrc.5
- doc/man/en/linkchecker.1
- doc/man/en/linkcheckerrc.5
- doc/src/man/linkcheckerrc.rst
- linkcheck/cache/results.py
- linkcheck/configuration/__init__.py
- linkcheck/director/__init__.py
- tests/cache/test_urlqueue.py
- tests/configuration/data/config0.ini
- tests/configuration/test_config.py
> Make ResultCache max_size configurable

- CONTRIBUTING.rst
- doc/src/code/index.rst
- doc/src/man/linkchecker.rst
- doc/src/man/linkcheckerrc.rst
- linkcheck/checker/__init__.py
- linkcheck/checker/fileurl.py
- linkcheck/checker/proxysupport.py
- linkcheck/checker/urlbase.py
- linkcheck/robotparser2.py
OK there are still a few external 403's.
Fixes #550.
> Make LinkChecker documentation pass a LinkChecker check

- .github/workflows/publish-docker.yml
- Dockerfile
- MANIFEST.in
- README.rst
- doc/development.md
- doc/src/conf.py
- setup.py
Ready to publicise now I think, but reviews welcome.
> Release new Docker image hosted on GitHub Packages

- setup.py
> Set minimum Beautiful Soup version in setup.py

- po/de.po
- po/es.po
- po/fr.po
- po/linkchecker.pot
- po/nl_NL.po
> Add Dutch translation

- linkcheck/checker/httpurl.py
> Update HttpUrl.encoding after following redirects

- .gitignore
- MANIFEST.in
- setup.cfg
- setup.py
Match the version reported using setuptools_scm.
Use the same git command as setuptools_scm uses for node_date.
> Set release date from HEAD

- .github/workflows/branch-man.yml
- .github/workflows/release-files.yml
Workflow to semi-automate man page and translation updates
Expected to be used form a fork, it will create a branch man-updates,
based on the upstream repository with additional commits with the updates.
Then a pull request would be created to send the updates upstream.
---
Workflow to automatically add Python distribution files to the release
> Workflows to automate updating man pages and create distribution files

- linkcheck/checker/__init__.py
- tests/checker/test_guess_url.py
Fixes:
linkchecker ftp.html
failing looking for ftp://ftp.html
> Don't guess the URL for files that end in .html

- .github/workflows/release-files.yml
Logs will be removed. PyPI will calculate and record checksums.
> Log checksums for release distribution files

- doc/changelog.txt
- doc/upgrading.txt
Time for a new release I think. Change log attached here. I won't merge this PR and make the release before 19:00&nbsp;UTC on Wednesday 22nd December.
As the other outstanding PRs are trivial I will merge them after one day and then give more of a chance for any problems to found.
> Release 10.1.0

- linkcheck/checker/unknownurl.py
- scripts/update_iana_uri_schemes.py
New MR for https://github.com/linkchecker/linkchecker/pull/612
I've created a new MR, as there are more changes then just the two new schemes
> Add Telegram and WhatsApp schemes

- README.rst
- doc/development.md
- doc/documentation.md
- doc/install.txt
A bit of detail in some commit messages.
> Assorted minor documentation updates
